server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.36.90.145:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowed-headers: "*"
            allow-credentials: false
      routes:
        - id: product-service
          uri: http://3.36.90.145:8081
          predicates:
            - Path=/products/**
        - id: order-service
          uri: http://3.36.90.145:8083
          predicates:
            - Path=/orders/**
        - id: cart-service
          uri: http://3.36.90.145:8084
          predicates:
            - Path=/carts/**
        - id: user-service
          uri: http://3.36.90.145:8085
          predicates:
            - Path=/users/**