server:
  port: 8761

eureka:
  instance:
    hostname: 13.209.13.212
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    serverUrl:
      defaultZone: http://13.209.13.212:8761/eureka/