server:
  port: 8761

eureka:
  instance:
    hostname: 3.36.90.145
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    serverUrl:
      defaultZone: http://3.36.90.145:8761/eureka/