server:
  port: 8084

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://3.36.90.145:3306/nolook?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#  datasource: # 내가 H2 DB 써서 일단 MySQL은 주석 쳐놨음
#    url: jdbc:h2:tcp://localhost/~/nolook
#    username: sa
#    password: 1234
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
  client:
    registerWithEureka: true
    fetchRegistry: true
  serviceUrl:
    defaultZone: http://3.36.90.145:8761/eureka/


